name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decrypt google-services.gpg
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$GOOGLE_SERVICES_GPG_PASSPHRASE" --output app/google-services.json app/google-services_enc.gpg
      env:
        GOOGLE_SERVICES_GPG_PASSPHRASE: ${{ secrets.GOOGLE_SERVICES_GPG_PASSPHRASE }}

    - name: Decrypt key.gpg
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$KEY_GPG_PASSPHRASE" --output app/src/main/res/raw/key.json app/src/main/res/raw/key_enc.gpg
      env:
        KEY_GPG_PASSPHRASE: ${{ secrets.KEY_GPG_PASSPHRASE }}

    - name: Build with Gradle
      run: ./gradlew build